name: Veracode Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

  
permissions:
  contents: read
  issues: write

jobs:
  security:
    name: Veracode Security Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Veracode Integration
        uses: veracode/github-actions-integration@v1

        with:
          veracode_config_path: ./veracode.yml

        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_KEY_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY_SECRET }}

  veracode_static_scan:
  push:
    trigger: true

    branches_to_run:
      - main
      - develop

  pull_request:
    trigger: true

    action:
      - opened
      - synchronize

    target_branch:
      - main

  # true = guarda resultados en Veracode Platform
  # false = scan efímero/local CI
  analysis_on_platform: false

  break_build_policy_findings: true
  break_build_invalid_policy: true
  break_build_on_error: true

  error_message: "Veracode SAST scan failed."

  policy: "Veracode Recommended Medium + SCA"

  # Mostrar findings en GitHub Security tab
  create_code_scanning_alert: true

  # Crear GitHub Issues automáticamente
  create_issue: true

  issues:
    trigger: false

    commands:
      - "Veracode Static Scan"

veracode_sca_scan:
  push:
    trigger: true

    branches_to_run:
      - main
      - develop

  pull_request:
    trigger: true

    action:
      - opened
      - synchronize

    target_branch:
      - main

  break_build_on_error: true
  break_build_policy_findings: true

  error_message: "Veracode SCA scan failed."

  issues:
    trigger: false

    commands:
      - "Veracode SCA Scan"

